# name = input ("Как вас зовут?\n")
# print ("1 ")
# print("11")
# print("111")
# print("я вам не мешаю?")
# name = input ("Как вас зовут?\n")
# otchestvo = input("Как ваше отчество?\n")
# print("Здравствуйте", name, otchestvo)
# vopros = input("Как зовут основателей компании Microsoft?\n")
# name2 = input("первый\n")
# name1 = input("второй\n")
# print(name2 ,"+", name1 ,"=", "друзья")
# vopros1 = input ("Как вас зовут?\n")
# print(vopros1,",","приятно познакомится","! \n")
# vopros2 = input ("чем вы тут занимаетесь?\n")
# print(vopros2,"это важно",",",vopros1,"! \n")
# vopros3 = input ("Каков ваш любимый цвет?\n")
# vopros4 = input("А какое ваше любимое животное?\n")
# print("Я придумал вам тотемное животное!","Это",vopros3,vopros4)
vopros1 = input ("Как вас зовут?\n")
print(vopros1,",","приятно познакомится","! \n")
vopros2 = input ("сколько вам лет?\n")
print(vopros2,"это хорошо",",",vopros1,"! \n")
vopros3 = input ("Каков ваш любимый цвет?\n")
print("а мой черный\n")
vopros4 = input("А какое ваше любимое животное?\n")
print("мое тоже\n")
print("Вас зовут",vopros1,".","Вам",vopros2,".","Ваш любимый цвет",vopros3,".","Ваше любимое животное",vopros4,".")

