# f = open('data.txt', 'r', encoding="utf-8")
# str1 = f.readline()
# str1 = str1.strip()
# str2 = f.readline()
# str2 = str2.strip()
# str3 = f.readline()
# str3 = str3.strip()
# print(str1,str2,str3)
# print("Вот ещё текст")
# f.close()
# f = open('data2.txt', 'r', encoding="utf-8")
# str1 = f.readline().strip()
# print("Сейчас текст в файле такой:", str1)
# f.close()
# 
# f = open('data2.txt', 'w', encoding="utf-8")
# str2 = input("Введите новый текст файла: ")
# f.write(str2)
# f.close()

# f = open('data.txt', 'r', encoding="utf-8")
# str1 = f.readline().strip()
# str2 = f.readline().strip()
# print(str1)
# print(str2)
# print("Вот ещё текст")
# f.close()


# f = open('data2.txt', 'r', encoding="utf-8")
# str1 = f.readline().strip()
# print("Сейчас текст в файле такой:", str1)
# f.close()
# 
# f = open('data2.txt', 'w', encoding="utf-8")
# str2 = input("Введите новый текст файла: ")
# f.write(str2)
# f.close()
psw = input("какой пароль ? ")
f = open('data.txt', 'r', encoding="utf-8")
Truepass = f.readline()
#f.readline = psw()
if psw == Truepass:
    print("всё верно")
else:
    print("ERROR")